apiVersion: v1
kind: Service
metadata:
  name:  http-service
spec:
  type: NodePort
  ports:
  - port:  80
    targetPort:  80
    protocol: TCP
    nodePort: 30036
  selector:
    name: httpd-frontend