#
kind: Service
apiVersion: v1
metadata:
  name: http-service
spec:
  selector:
    name: httpd-frontend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 32321
  type: NodePort