apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
  labels:
    name: result
    app: demo-voting-app
spec:
  replicas: 1
  template:
    metadata:
      name: result-app
      labels:
        name: result
        app: demo-voting-app
    spec:
      containers:
      - name: result
        image: kodekloud/examplevotingapp_result:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: demo-voting-app
---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name:  result-service
    app: demo-voting-app
spec:
  selector:
    name: result
    app: demo-voting-app
  type: NodePort
  ports:
  - name: result
    port: 80
    targetPort: 80
    nodePort: 30040