apiVersion: v1
kind: Pod
metadata:
  name: postgres-app
  labels:
    name: db
    app: demo-voting-app
spec:
  containers:
  - name: db
    image: postgres:9.4
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    env:
    - name: POSTGRES_USER
      value: "postgres"
    - name:  POSTGRES_PASSWORD
      value: "postgres"
    - name: POSTGRES_HOST_AUTH_METHOD
      value: trust
    ports:
      - containerPort: 5432
        name: db