apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db
    app: demo-voting-app
spec:
  type: ClusterIP
  ports:
  - name: db-service
    port: 5432
    protocol: TCP
    targetPort:  5432
  selector:
    name: db
    app: demo-voting-app