apiVersion: v1
kind: Pod
metadata:
  name: redis-app
  labels:
    name: redis
    app: demo-voting-app
spec:
  containers:
  - name: redis
    image: redis:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 6379

