apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name:  redis-service
    app: demo-voting-app
spec:
  selector:
    name: redis
    app: demo-voting-app
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort:  6379