apiVersion: v1
kind: Pod
metadata:
  name: worker-app
  labels:
    name: worker
    app: demo-voting-app
spec:
  containers:
  - name: worker
    image: panasonixme/votingappworker
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"

